### ISSUE TITLE
Instance Transforms 

### ISSUE THREAD

**Issue by Chrjstoph** [ingowald/pbrt-parser#2]
Hi again,

I am slowly coming to terms with pbrt and your parser.

I wish to render using GPU instances, which means I want to duplicate the PBRT structure as lean as possible.

I have noticed that the duplication of Objects, is done via:

AttributeBegin
    Transform [16]
    ObjectInstance "..."
AttributeEnd

Your parser/ scene proviodes objects(I have only world, yet) and object instances together with their affine transforms "xfm".
Do you also provide a translation vector, or rather the entire transform matrix? or am I missing something essential?

**Comment by Chrjstoph** [comment]
Never mind. I'm daft.

**Comment by Chrjstoph** [comment]
Reiterating on my previous thought I find that I have problems identifying objects, namely the individual objects of the world.

The world has instances and shapes.
The instances have objects.

But where are the objects that group the shapes?

Best Regards
Christoph

**Comment by ingowald** [comment]
Note this is not how "my" parser does things; it's merely the way that the PBRT file format works. I, too, may not entirely agree with every little detail of how that file format works (I'd do a few things differently, too), but in that stage of the parser I - intentionally - do mess with the data, and only read exactly what is in the file.

As to your specific question: 
- the parser returns a scene; that scene has - among a lot of other stuff that configure the rendering - a 'world' object
- that 'world' is a object, and as such has two lists of things that define geometry:
a) some 'shapes' as direct part of that object; and
b) some object 'instances' that refer - with a transform - to other objects (recursively)

shapes also have transforms, but those apply only that shape; the transforms stored in object instances apply to the entire child object, and all the shapes and ohter objects that this child object contains (ie, to the entire tree below that object).

**Comment by Chrjstoph** [comment]
I see.

I thought that there should be an object list. Denoting the children of each object.

As I understand it now, and as you describe it, there are instances that have objects with <instanced> shapes.

An additional list of objects with shapes, each with a list of transformations sounds practical from a GL point of view. 
But thats easily done on the application side using maps.

So, thank you for your explanations and library. 
Once I have my instanced rendering pipeline running, I have a look at the materials.


Btw, is there a way to encode & describe the foliage placement procedurally, 8Floats per leaf is stil rather excessive.

**Comment by ingowald** [comment]
On 02/03/2017 10:32 AM, Christoph wrote:
> I see.
>
> I thought that there should be an object list. Denoting the children 
> of each object.

Well, yes, there is; it just depends on what "kind" of chilren they are.
Each child can be either
a) a shape that's referenced directly, or
b) a entire "group" of objects that may be instantiated.

The former appear directly in the Object::shapes vector; each such shape 
has a transform attached to (just like instances), but that transform 
belongs to that specific shape. In particular, that shape will not 
(directly) be referenced by anybody else, with a different transform, 
etc (the obejct that contains a shape may be referenced/instantiated 
multiple times, but each shape is _directly_ only referenced once, by 
the (one) object that contains it.

The latter - 'object instances' - appear in the Object::objectInstances 
vector, each such object has a transform, as well as a reference to 
another object; the specific object referenced by a given instnace _may_ 
be linked to by multiple different instances (each with a different 
transform).

In other words: every shape has exactly one unique object that "owns" 
it; but objects can be intantiated, and can have multiple 
object::instnace's point to them from different locatoins. If a given 
triangle mesh needs to be instanced, then PBRT will put it into an 
object, and instantiate this object. I now this is confusing - in 
particular because geometries can have transforms, too - but that's the 
way PBRT does it. And again - that's not how I chose to organize the 
data, that's the way the PBRT files do; the parser just parses it :-).

Cheers,

Ingo

PS: Note that differentiation between objects and shapes actually makes 
a lot of sense. Very often the same "logical" object will consist of 
multiple different shapes (eac with a different material, and/or 
different sets of texture coordinates etcpp); in that case they'd all be 
in the same 'object', with one shape per material, per set of tex 
coords, etcpp.

**Comment by Chrjstoph** [comment]
Is there a definitive way to discern whether geometry has an object or not?
Or rather are the shapes of the root all the shapes of the entire scene?
It would seem that way, that would also explain the rcp() in your writing procedure, so that you can add additional instances.
But all rather confusing

**Comment by Chrjstoph** [comment]
Oh boy.

So considering the smg scene.

The root/world “object” has shapes, belonging to the world. Those shapes won’t be duplicated in other objects.

The the world has instances of (possibly multiple) objects, and each object has shapes, etc. recursion etc.


I am just curious that, when rendering just the shapes of smg, that there are some leaves on the tree.
