### ISSUE TITLE
Resolving Materialname of Shape

### ISSUE THREAD

**Issue by Chrjstoph** [ingowald/pbrt-parser#5]
Hi again,

I might be too hasty, but I have problems mapping Materials to shapes.

It appears that the Parser returns the material itself, omitting the material name, thus making nonredundant material storage ... difficult.

I dont know which would be better, for the material to sport its own name, or the shape carying the name along side the data.

Or am I missing something?

**Comment by ingowald** [comment]
The scene has a 
   std::map<std::string,std::shared_ptr<Material> > namedMaterial;
that contains all materials that do have names.
I did not add a 'name' field to the material because not all materials do have names (in fact, in many scenes most do not). 
That 'namedmaterials' is typically used to look up material by name, not name by material, but it shouldn't be too hard to add that; or copy every element in that list to your own material-to-name mapper.

**Comment by Chrjstoph** [comment]
I have modified the parser to define an incrementing Name.
